# Generated by Django 4.2.14 on 2024-10-04 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nana', '0005_competition_essaytopic_essay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaytopic',
            name='winner',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
